name: Deploy to Firebase Hosting on PR
'on':
  pull_request:
    paths:
      - 'capstone-project-vue'
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies and build
        working-directory: ./capstone-project-vue
        run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAPSTONE_PROJECT_PWEBER }}'
          projectId: capstone-project-pweber
