name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
    paths:
      - 'capstone-project-vue/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies and build
        run: npm ci && npm run build
        working-directory: ./capstone-project-vue

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: ./capstone-project-vue
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAPSTONE_PROJECT_PWEBER }}'
          channelId: live
          projectId: capstone-project-pweber
